stages:
  - test
  - deploy

test:
  stage: test
  image: node:18
  script:
    - npm install
    - npm run test
  only:
    - main

deploy:
  stage: deploy
  image: node:18
  script:
    - npm install
    - npm run build
    - curl -X POST -F "token=$RENDER_API_TOKEN" -F "ref=main" "https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys"
  only:
    - main